# Just apply Travis-CI for these branches
branches:
  only:
  - master
  - experimental

# Use Ubuntu 14.04 Trusty
dist: trusty

language: node_js

# DOC: http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
matrix:
  include:
    - os: linux
      node_js: 8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: linux
      node_js: 9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      node_js: 8
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - npm install

before_script:
  - npm install -g gulp-cli

script:
  - gulp lint:node
  - gulp tidy
  - gulp test

notifications:
  email:
    recipients:
      - ibc@aliax.net
      - jmillan@aliax.net
    on_success: change
    on_failure: always
